<?php

// Array of europe country codes with thier names in native language
	$europe_native = array( 'at' => 'Österreich', 
                          'be' => 'Belgien',
                          'bg' => 'България',
                          'by' => 'Беларусь',
                          'ch' => 'Schweiz',
                          'cz' => 'Česko',
                          'de' => 'Deutschland',
                          'dk' => 'Danmark',
                          'ee' => 'Eesti',
                          'es' => 'España',
                          'fi' => 'Suomi',
                          'fr' => 'France',
                          'gr' => 'Ελλάδα',
                          'hr' => 'Hrvatska',
                          'hu' => 'Magyarország',
                          'ie' => 'Ireland/Éire',
                          'is' => 'Ísland',
                          'it' => 'Italia',
                          'li' => 'Liechtenstein',
                          'lt' => 'Lietuva',
                          'lu' => 'Luxemburg',
                          'lv' => 'Latvija',
                          'me' => 'Црна Гор',
                          'mt' => 'Malta',
                          'nl' => 'Nederland',
                          'no' => 'Norge',
                          'pl' => 'Polska',
                          'pt' => 'Portugal',
                          'ro' => 'România',
                          'rs' => 'Србија',
                          'ru' => 'Россия',
                          'se' => 'Sverige',
                          'si' => 'Slovenija',
                          'sk' => 'Slovensko',
                          'tr' => 'Türkiye',
                          'ua' => 'Україна',
                          'uk' => 'United Kingdom'
                          );

// Array of europe country codes with thier names in english language, just for admin panel to manage it easy
	$europe_english = array( 'at' => __('Austria', 'mnet-langbf'), 
                          'be' => __('Belgium', 'mnet-langbf'),
                          'bg' => __('Bulgaria', 'mnet-langbf'),
                          'by' => __('Belarus', 'mnet-langbf'),
                          'ch' => __('Switzerland', 'mnet-langbf'),
                          'cz' => __('Czech Republic', 'mnet-langbf'),
                          'de' => __('Germany', 'mnet-langbf'),
                          'dk' => __('Denmark', 'mnet-langbf'),
                          'ee' => __('Estonia', 'mnet-langbf'),
                          'es' => __('Spain', 'mnet-langbf'),
                          'fi' => __('Finland', 'mnet-langbf'),
                          'fr' => __('France', 'mnet-langbf'),
                          'gr' => __('Greece', 'mnet-langbf'),
                          'hr' => __('Croatia', 'mnet-langbf'),
                          'hu' => __('Hungary', 'mnet-langbf'),
                          'ie' => __('Ireland', 'mnet-langbf'),
                          'is' => __('Iceland', 'mnet-langbf'),
                          'it' => __('Italy', 'mnet-langbf'),
                          'li' => __('Liechtenstein', 'mnet-langbf'),
                          'lt' => __('Lithuania', 'mnet-langbf'),
                          'lu' => __('Luxembourg', 'mnet-langbf'),
                          'lv' => __('Latvia', 'mnet-langbf'),
                          'me' => __('Montenegro', 'mnet-langbf'),
                          'mt' => __('Malta', 'mnet-langbf'),
                          'nl' => __('Netherlands', 'mnet-langbf'),
                          'no' => __('Norway', 'mnet-langbf'),
                          'pl' => __('Poland', 'mnet-langbf'),
                          'pt' => __('Portugal', 'mnet-langbf'),
                          'ro' => __('Romania', 'mnet-langbf'),
                          'rs' => __('Serbia', 'mnet-langbf'),
                          'ru' => __('Russian Federation', 'mnet-langbf'),
                          'se' => __('Sweden', 'mnet-langbf'),
                          'si' => __('Slovenia', 'mnet-langbf'),
                          'sk' => __('Slovakia', 'mnet-langbf'),
                          'tr' => __('Turkey', 'mnet-langbf'),
                          'ua' => __('Ukraine', 'mnet-langbf'),
                          'uk' => __('United Kingdom', 'mnet-langbf')
                          );

// Array of americas country codes with thier names in native language
	$america_native = array( 'ar' => 'Argentina', 
                          'bs' => 'Bahamas',
                          'bb' => 'Barbados',
                          'bz' => 'Belize',
                          'bo' => 'Bolivia',
                          'br' => 'Brasil',
                          'ca' => 'Canada',
                          'cl' => 'Chile',
                          'co' => 'Colombia',
                          'cr' => 'Costa Rica',
                          'cu' => 'Cuba',
                          'dm' => 'Dominique',
                          'do' => 'República Dominicana',
                          'ec' => 'Ecuador',
                          'sv' => 'El Salvador',
                          'gd' => 'Grenada',
                          'gt' => 'Guatemala',
                          'gy' => 'Guyana',
                          'ht' => 'Haïti',
                          'hn' => 'Honduras',
                          'jm' => 'Jamaica',
                          'mx' => 'México',
                          'ni' => 'Nicaragua',
                          'pa' => 'Panamá',
                          'py' => 'Paraguay',
                          'pe' => 'Perú',
                          'pr' => 'Puerto Rico',
                          'sr' => 'Suriname',
                          'tt' => 'Trinidad and Tobago',
                          'us' => 'United States',
                          'uy' => 'Uruguay',
                          've' => 'Venezuela'
                          );

// Array of americas country codes with thier names in english language, just for admin panel to manage it easy
	$america_english = array( 'ar' => __('Argentina', 'mnet-langbf'), 
                          'bs' => __('Bahamas', 'mnet-langbf'),
                          'bb' => __('Barbados', 'mnet-langbf'),
                          'bz' => __('Belize', 'mnet-langbf'),
                          'bo' => __('Bolivia', 'mnet-langbf'),
                          'br' => __('Brazil', 'mnet-langbf'),
                          'ca' => __('Canada', 'mnet-langbf'),
                          'cl' => __('Chile', 'mnet-langbf'),
                          'co' => __('Colombia', 'mnet-langbf'),
                          'cr' => __('Costa Rica', 'mnet-langbf'),
                          'cu' => __('Cuba', 'mnet-langbf'),
                          'dm' => __('Dominica', 'mnet-langbf'),
                          'do' => __('Dominican Republic', 'mnet-langbf'),
                          'ec' => __('Ecuador', 'mnet-langbf'),
                          'sv' => __('El Salvador', 'mnet-langbf'),
                          'gd' => __('Grenada', 'mnet-langbf'),
                          'gt' => __('Guatemala', 'mnet-langbf'),
                          'gy' => __('Guyana', 'mnet-langbf'),
                          'ht' => __('Haiti', 'mnet-langbf'),
                          'hn' => __('Honduras', 'mnet-langbf'),
                          'jm' => __('Jamaica', 'mnet-langbf'),
                          'mx' => __('Mexico', 'mnet-langbf'),
                          'ni' => __('Nicaragua', 'mnet-langbf'),
                          'pa' => __('Panama', 'mnet-langbf'),
                          'py' => __('Paraguay', 'mnet-langbf'),
                          'pe' => __('Peru', 'mnet-langbf'),
                          'pr' => __('Puerto Rico', 'mnet-langbf'),
                          'sr' => __('Suriname', 'mnet-langbf'),
                          'tt' => __('Trinidad and Tobago', 'mnet-langbf'),
                          'us' => __('United States', 'mnet-langbf'),
                          'uy' => __('Uruguay', 'mnet-langbf'),
                          've' => __('Venezuela', 'mnet-langbf')
                          );

//TODO: Asia + Australia and Africa

?>