<?php

// Array of europe country codes with thier names in native language
	$europe_native = array( 'at' => 'Österreich', 
                          'be' => 'Belgien',
                          'bg' => 'България',
                          'by' => 'Беларусь',
                          'ch' => 'Schweiz',
                          'cz' => 'Česko',
                          'de' => 'Deutschland',
                          'dk' => 'Danmark',
                          'ee' => 'Eesti',
                          'es' => 'España',
                          'fi' => 'Suomi',
                          'fr' => 'France',
                          'gr' => 'Ελλάδα',
                          'hr' => 'Hrvatska',
                          'hu' => 'Magyarország',
                          'ie' => 'Ireland/Éire',
                          'is' => 'Ísland',
                          'it' => 'Italia',
                          'li' => 'Liechtenstein',
                          'lt' => 'Lietuva',
                          'lu' => 'Luxemburg',
                          'lv' => 'Latvija',
                          'me' => 'Црна Гор',
                          'mt' => 'Malta',
                          'nl' => 'Nederland',
                          'no' => 'Norge',
                          'pl' => 'Polska',
                          'pt' => 'Portugal',
                          'ro' => 'România',
                          'rs' => 'Србија',
                          'ru' => 'Россия',
                          'se' => 'Sverige',
                          'si' => 'Slovenija',
                          'sk' => 'Slovensko',
                          'tr' => 'Türkiye',
                          'ua' => 'Україна',
                          'uk' => 'United Kingdom'
                          );

// Array of europe country codes with thier names in english language, just for admin panel to manage it easy
	$europe_english = array( 'at' => __('Austria', 'mnet-langbf'), 
                          'be' => __('Belgium', 'mnet-langbf'),
                          'bg' => __('Bulgaria', 'mnet-langbf'),
                          'by' => __('Belarus', 'mnet-langbf'),
                          'ch' => __('Switzerland', 'mnet-langbf'),
                          'cz' => __('Czech Republic', 'mnet-langbf'),
                          'de' => __('Germany', 'mnet-langbf'),
                          'dk' => __('Denmark', 'mnet-langbf'),
                          'ee' => __('Estonia', 'mnet-langbf'),
                          'es' => __('Spain', 'mnet-langbf'),
                          'fi' => __('Finland', 'mnet-langbf'),
                          'fr' => __('France', 'mnet-langbf'),
                          'gr' => __('Greece', 'mnet-langbf'),
                          'hr' => __('Croatia', 'mnet-langbf'),
                          'hu' => __('Hungary', 'mnet-langbf'),
                          'ie' => __('Ireland', 'mnet-langbf'),
                          'is' => __('Iceland', 'mnet-langbf'),
                          'it' => __('Italy', 'mnet-langbf'),
                          'li' => __('Liechtenstein', 'mnet-langbf'),
                          'lt' => __('Lithuania', 'mnet-langbf'),
                          'lu' => __('Luxembourg', 'mnet-langbf'),
                          'lv' => __('Latvia', 'mnet-langbf'),
                          'me' => __('Montenegro', 'mnet-langbf'),
                          'mt' => __('Malta', 'mnet-langbf'),
                          'nl' => __('Netherlands', 'mnet-langbf'),
                          'no' => __('Norway', 'mnet-langbf'),
                          'pl' => __('Poland', 'mnet-langbf'),
                          'pt' => __('Portugal', 'mnet-langbf'),
                          'ro' => __('Romania', 'mnet-langbf'),
                          'rs' => __('Serbia', 'mnet-langbf'),
                          'ru' => __('Russian Federation', 'mnet-langbf'),
                          'se' => __('Sweden', 'mnet-langbf'),
                          'si' => __('Slovenia', 'mnet-langbf'),
                          'sk' => __('Slovakia', 'mnet-langbf'),
                          'tr' => __('Turkey', 'mnet-langbf'),
                          'ua' => __('Ukraine', 'mnet-langbf'),
                          'uk' => __('United Kingdom', 'mnet-langbf')
                          );

// Array of americas country codes with thier names in native language
	$america_native = array( 'ar' => 'Argentina', 
                          'bs' => 'Bahamas',
                          'bb' => 'Barbados',
                          'bz' => 'Belize',
                          'bo' => 'Bolivia',
                          'br' => 'Brasil',
                          'ca' => 'Canada',
                          'cl' => 'Chile',
                          'co' => 'Colombia',
                          'cr' => 'Costa Rica',
                          'cu' => 'Cuba',
                          'dm' => 'Dominique',
                          'do' => 'República Dominicana',
                          'ec' => 'Ecuador',
                          'sv' => 'El Salvador',
                          'gd' => 'Grenada',
                          'gt' => 'Guatemala',
                          'gy' => 'Guyana',
                          'ht' => 'Haïti',
                          'hn' => 'Honduras',
                          'jm' => 'Jamaica',
                          'mx' => 'México',
                          'ni' => 'Nicaragua',
                          'pa' => 'Panamá',
                          'py' => 'Paraguay',
                          'pe' => 'Perú',
                          'pr' => 'Puerto Rico',
                          'sr' => 'Suriname',
                          'tt' => 'Trinidad and Tobago',
                          'us' => 'United States',
                          'uy' => 'Uruguay',
                          've' => 'Venezuela'
                          );

// Array of americas country codes with thier names in english language, just for admin panel to manage it easy
	$america_english = array( 'ar' => __('Argentina', 'mnet-langbf'), 
                          'bs' => __('Bahamas', 'mnet-langbf'),
                          'bb' => __('Barbados', 'mnet-langbf'),
                          'bz' => __('Belize', 'mnet-langbf'),
                          'bo' => __('Bolivia', 'mnet-langbf'),
                          'br' => __('Brazil', 'mnet-langbf'),
                          'ca' => __('Canada', 'mnet-langbf'),
                          'cl' => __('Chile', 'mnet-langbf'),
                          'co' => __('Colombia', 'mnet-langbf'),
                          'cr' => __('Costa Rica', 'mnet-langbf'),
                          'cu' => __('Cuba', 'mnet-langbf'),
                          'dm' => __('Dominica', 'mnet-langbf'),
                          'do' => __('Dominican Republic', 'mnet-langbf'),
                          'ec' => __('Ecuador', 'mnet-langbf'),
                          'sv' => __('El Salvador', 'mnet-langbf'),
                          'gd' => __('Grenada', 'mnet-langbf'),
                          'gt' => __('Guatemala', 'mnet-langbf'),
                          'gy' => __('Guyana', 'mnet-langbf'),
                          'ht' => __('Haiti', 'mnet-langbf'),
                          'hn' => __('Honduras', 'mnet-langbf'),
                          'jm' => __('Jamaica', 'mnet-langbf'),
                          'mx' => __('Mexico', 'mnet-langbf'),
                          'ni' => __('Nicaragua', 'mnet-langbf'),
                          'pa' => __('Panama', 'mnet-langbf'),
                          'py' => __('Paraguay', 'mnet-langbf'),
                          'pe' => __('Peru', 'mnet-langbf'),
                          'pr' => __('Puerto Rico', 'mnet-langbf'),
                          'sr' => __('Suriname', 'mnet-langbf'),
                          'tt' => __('Trinidad and Tobago', 'mnet-langbf'),
                          'us' => __('United States', 'mnet-langbf'),
                          'uy' => __('Uruguay', 'mnet-langbf'),
                          've' => __('Venezuela', 'mnet-langbf')
                          );

// Array of asia country codes with thier names in native language
	$asia_native = array( 'af' => 'افغانستان',
                          'am' => 'Հայաստան',
                          'au' => 'Australia',
                          'az' => 'Azərbaycan',
                          'bh' => '‏البحرين',
                          'bd' => 'বাংলাদেশ',
                          'bt' => 'འབྲུག་ཡུལ་',
                          'bn' => 'نڬارا بروني دارالسلام',
                          'kh' => 'Kâmpŭchéa',
                          'cn' => '中国/中华',
                          'cy' => 'Κύπρος',
                          'ge' => 'საქართველო',
                          'hk' => '香港',
                          'in' => 'भारत गणराज्य',
                          'id' => 'Indonesia',
                          'ir' => 'ایران',
                          'iq' => 'العراق',
                          'il' => 'מְדִינַת יִשְׂרָאֵל',
                          'jp' => '日本',
                          'jo' => 'اَلأُرْدُن',
                          'kz' => 'Қазақстан',
                          'kw' => 'دولة الكويت',
                          'kg' => 'Кыргызстан',
                          'la' => 'ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ',
                          'lb' => 'لُبْنَان',
                          'my' => 'Malaysia',
                          'mv' => 'ދިވެހިރާއްޖެ',
                          'mn' => 'Монгол улс',
                          'mm' => 'Myanmar',
                          'np' => 'नेपाल',
                          'nz' => 'New Zealand',
                          'kp' => '朝鮮民主主義人民共和國',
                          'om' => 'عمان',
                          'pk' => 'پاکِستان',
                          'pg' => 'Papua Niugini',
                          'ph' => 'Pilipinas',
                          'qa' => 'قطر',
                          'sa' => 'العربية السعودية',
                          'sg' => 'Singapore',
                          'kr' => '大韓民國',
                          'lk' => 'ශ්‍රී ලංකා',
                          'sy' => 'سورية',
                          'tw' => '台灣',
                          'tj' => 'Тоҷикистон',
                          'th' => 'ประเทศไทย',
                          'tl' => 'Timór Lorosa\'e',
                          'tm' => 'Türkmenistan',
                          'ae' => 'دولة الإمارات العربية المتحدة',
                          'uz' => 'O‘zbekiston',
                          'vn' => 'Việt Nam',
                          'ye' => 'الجمهورية اليمنية'
                          );

// Array of asia country codes with thier names in english language, just for admin panel to manage it easy
	$asia_english = array( 'af' => __('Afghanistan', 'mnet-langbf'), 
                          'am' => __('Armenia', 'mnet-langbf'),
                          'au' => __('Australia', 'mnet-langbf'),
                          'az' => __('Azerbaijan', 'mnet-langbf'),
                          'bh' => __('Bahrain', 'mnet-langbf'),
                          'bd' => __('Bangladesh', 'mnet-langbf'),
                          'bt' => __('Bhutan', 'mnet-langbf'),
                          'bn' => __('Brunei', 'mnet-langbf'),
                          'kh' => __('Cambodia', 'mnet-langbf'),
                          'cn' => __('China', 'mnet-langbf'),
                          'cy' => __('Cyprus', 'mnet-langbf'),
                          'ge' => __('Georgia', 'mnet-langbf'),
                          'hk' => __('Hong Kong', 'mnet-langbf'),
                          'in' => __('India', 'mnet-langbf'),
                          'id' => __('Indonesia', 'mnet-langbf'),
                          'ir' => __('Iran', 'mnet-langbf'),
                          'iq' => __('Iraq', 'mnet-langbf'),
                          'il' => __('Israel', 'mnet-langbf'),
                          'jp' => __('Japan', 'mnet-langbf'),
                          'jo' => __('Jordan', 'mnet-langbf'),
                          'kz' => __('Kazakhstan', 'mnet-langbf'),
                          'kw' => __('Kuwait', 'mnet-langbf'),
                          'kg' => __('Kyrgyzstan', 'mnet-langbf'),
                          'la' => __('Laos', 'mnet-langbf'),
                          'lb' => __('Lebanon', 'mnet-langbf'),
                          'my' => __('Malaysia', 'mnet-langbf'),
                          'mv' => __('Maldives', 'mnet-langbf'),
                          'mn' => __('Mongolia', 'mnet-langbf'),
                          'mm' => __('Myanmar', 'mnet-langbf'),
                          'np' => __('Nepal', 'mnet-langbf'),
                          'nz' => __('New Zealand', 'mnet-langbf'),
                          'kp' => __('North Korea', 'mnet-langbf'),
                          'om' => __('Oman', 'mnet-langbf'),
                          'pk' => __('Pakistan', 'mnet-langbf'),
                          'pg' => __('Papua New Guinea', 'mnet-langbf'),
                          'ph' => __('Philippines', 'mnet-langbf'),
                          'qa' => __('Qatar', 'mnet-langbf'),
                          'sa' => __('Saudi Arabia', 'mnet-langbf'),
                          'sg' => __('Singapore', 'mnet-langbf'),
                          'kr' => __('South Korea', 'mnet-langbf'),
                          'lk' => __('Sri Lanka', 'mnet-langbf'),
                          'sy' => __('Syria', 'mnet-langbf'),
                          'tw' => __('Taiwan', 'mnet-langbf'),
                          'tj' => __('Tajikistan', 'mnet-langbf'),
                          'th' => __('Thailand', 'mnet-langbf'),
                          'tl' => __('Timor-Leste', 'mnet-langbf'),
                          'tm' => __('Turkmenistan', 'mnet-langbf'),
                          'ae' => __('United Arab Emirates', 'mnet-langbf'),
                          'uz' => __('Uzbekistan', 'mnet-langbf'),
                          'vn' => __('Vietnam', 'mnet-langbf'),
                          'ye' => __('Yemen', 'mnet-langbf')
                          );


// Array of africa country codes with thier names in native language
	$africa_native = array( 'dz' => 'الجزائر‎',
                          'ao' => 'Angola',
                          'bj' => 'Bénin',
                          'bw' => 'Botswana',
                          'bf' => 'Burkina Faso',
                          'bi' => 'Burundi',
                          'cm' => 'Cameroun',
                          'cv' => 'Cabo Verde',
                          'cf' => 'Centrafrique',
                          'td' => 'Tchad',
                          'km' => 'Union des Comores',
                          'cg' => 'République du Congo',
                          'cd' => 'République démocratique du Congo',
                          'ci' => 'Côte d\'Ivoire',
                          'dj' => 'Djibouti',
                          'eg' => 'مصر',
                          'gq' => 'Guinea Ecuatorial',
                          'er' => 'ኤርትራ',
                          'et' => 'ኢትዮጵያ',
                          'ga' => 'Gabon',
                          'gm' => 'Gambia',
                          'gh' => 'Ghana',
                          'gn' => 'Guinea',
                          'gw' => 'Guiné-Bissau',
                          'ke' => 'Kenya',
                          'ls' => 'Lesotho',
                          'lr' => 'Liberia',
                          'ly' => 'ليبيا‎',
                          'mg' => 'Madagasikara',
                          'mw' => 'Malawi',
                          'ml' => 'Mali',
                          'mr' => 'موريتانيا',
                          'mu' => 'Moris',
                          'ma' => 'المغرب‎',
                          'mz' => 'Moçambique',
                          'na' => 'Namibia',
                          'ne' => 'Niger',
                          'ng' => 'Nigeria',
                          'rw' => 'Rwanda',
                          'st' => 'São Tomé and Príncipe',
                          'sn' => 'le Sénégal',
                          'sc' => 'Seychelles',
                          'sl' => 'Sierra Leone',
                          'so' => 'Soomaaliya',
                          'za' => 'South Africa',
                          'sd' => 'السودان‎',
                          'sz' => 'Swaziland',
                          'tz' => 'Tanzania',
                          'tg' => 'Togo',
                          'tn' => 'تونس‎',
                          'ug' => 'Uganda',
                          'zm' => 'Zambia',
                          'zw' => 'Zimbabwe'
                          );

// Array of africa country codes with thier names in english language, just for admin panel to manage it easy
	$africa_english = array( 'dz' => __('Algeria', 'mnet-langbf'), 
                          'ao' => __('Angola', 'mnet-langbf'),
                          'bj' => __('Benin', 'mnet-langbf'),
                          'bw' => __('Botswana', 'mnet-langbf'),
                          'bf' => __('Burkina Faso', 'mnet-langbf'),
                          'bi' => __('Burundi', 'mnet-langbf'),
                          'cm' => __('Cameroon', 'mnet-langbf'),
                          'cv' => __('Cape Verde', 'mnet-langbf'),
                          'cf' => __('Central African Republic', 'mnet-langbf'),
                          'td' => __('Chad', 'mnet-langbf'),
                          'km' => __('Comoros', 'mnet-langbf'),
                          'cg' => __('Republic of the Congo', 'mnet-langbf'),
                          'cd' => __('Democratic Republic of the Congo', 'mnet-langbf'),
                          'ci' => __('Côte d\'Ivoire', 'mnet-langbf'),
                          'dj' => __('Djibouti', 'mnet-langbf'),
                          'eg' => __('Egypt', 'mnet-langbf'),
                          'gq' => __('Equatorial Guinea', 'mnet-langbf'),
                          'er' => __('Eritrea', 'mnet-langbf'),
                          'et' => __('Ethiopia', 'mnet-langbf'),
                          'ga' => __('Gabon', 'mnet-langbf'),
                          'gm' => __('Gambia', 'mnet-langbf'),
                          'gh' => __('Ghana', 'mnet-langbf'),
                          'gn' => __('Guinea', 'mnet-langbf'),
                          'gw' => __('Guinea-Bissau', 'mnet-langbf'),
                          'ke' => __('Kenya', 'mnet-langbf'),
                          'ls' => __('Lesotho', 'mnet-langbf'),
                          'lr' => __('Liberia', 'mnet-langbf'),
                          'ly' => __('Libya', 'mnet-langbf'),
                          'mg' => __('Madagascar', 'mnet-langbf'),
                          'mw' => __('Malawi', 'mnet-langbf'),
                          'ml' => __('Mali', 'mnet-langbf'),
                          'mr' => __('Mauritania', 'mnet-langbf'),
                          'mu' => __('Mauritius', 'mnet-langbf'),
                          'ma' => __('Morocco', 'mnet-langbf'),
                          'mz' => __('Mozambique', 'mnet-langbf'),
                          'na' => __('Namibia', 'mnet-langbf'),
                          'ne' => __('Niger', 'mnet-langbf'),
                          'ng' => __('Nigeria', 'mnet-langbf'),
                          'rw' => __('Rwanda', 'mnet-langbf'),
                          'st' => __('São Tomé and Príncipe', 'mnet-langbf'),
                          'sn' => __('Senegal', 'mnet-langbf'),
                          'sc' => __('Seychelles', 'mnet-langbf'),
                          'sl' => __('Sierra Leone', 'mnet-langbf'),
                          'so' => __('Somalia', 'mnet-langbf'),
                          'za' => __('South Africa', 'mnet-langbf'),
                          'sd' => __('Sudan', 'mnet-langbf'),
                          'sz' => __('Swaziland', 'mnet-langbf'),
                          'tz' => __('Tanzania', 'mnet-langbf'),
                          'tg' => __('Togo', 'mnet-langbf'),
                          'tn' => __('Tunisia', 'mnet-langbf'),
                          'ug' => __('Uganda', 'mnet-langbf'),
                          'zm' => __('Zambia', 'mnet-langbf'),
                          'zw' => __('Zimbabwe', 'mnet-langbf')
                          );

/* TODO */
// AFRICA
//                          'ic' => __('Canary Islands', 'mnet-langbf'),
//                          'es-ce' => __('Ceuta', 'mnet-langbf'),
//                          'pt-30' => __('Madeira', 'mnet-langbf'),
//                          'yt' => __('Mayotte', 'mnet-langbf'),
//                          'es-ml' => __('Melilla', 'mnet-langbf'),
//                          're' => __('Réunion', 'mnet-langbf'),
//                          'eh' => __('Sahrawi Arab Democratic Republic', 'mnet-langbf'),
//                          'sh' => __('Saint Helena', 'mnet-langbf'),
//                          'ss' => __('South Sudan', 'mnet-langbf'),

?>